### ISSUE TITLE
Add event venues

### ISSUE THREAD

**Issue by antsmo** [MyGuySi/dev-wales#13]
Details coming soon...

## Tasks

- [x] Add DB table (dev)
- [ ] Add API controller
- [ ] Add router
- [ ] Add HTML template
- [x] Add DB table (live)
